version: 2
updates:
- package-ecosystem: bundler
  directory: "/ruby"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
