# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: umbra.proto

require 'google/protobuf'


descriptor_data = "\n\x0bumbra.proto\x12\x08umbra.pb\"\x95\x01\n\x07Message\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12/\n\x07headers\x18\x03 \x03(\x0b\x32\x1e.umbra.pb.Message.HeadersEntry\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x1cZ\x1agithub.com/carwow/umbra/pbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Umbra
  module Pb
    Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("umbra.pb.Message").msgclass
  end
end
