name: Test & Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  protoc:
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-protoc@v3
        with:
          version: 29.3
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.22
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go
      - run: protoc -I=. --go_out=pb --go_opt=paths=source_relative --ruby_out=ruby/lib/umbra/pb ./umbra.proto
      - run: git add . && git diff --staged --exit-code

  golang:
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    name: Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.22
    - uses: actions/checkout@v2
    - run: go mod tidy -v && git diff --exit-code go.mod go.sum
    - run: go build -v .
    - run: go test -v ./...

  ruby:
    defaults:
      run:
        working-directory: ./ruby
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2', '3.4' ]
        experimental: [ false ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec standardrb
      - run: bundle exec rspec --format progress
